{{- if .Values.storage.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-hf-cache
spec:
  accessModes: [{{ .Values.storage.accessMode }}]
  {{- with .Values.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
